version: "3"
services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    
    ports:
      - "8080:8080"  
    container_name: node-api  
    volumes:
      - .:/api/app
    
  dashboard:
    build: 
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/dashboard/app
     
    stdin_open: true   
 
  